algorithm:
  num_particles: 1000
  sigma:
    dx: 0.02
    dy: 0.02
    dyaw: 0.03
    laser:
      hit: 1.0
  cell_full_threshold: 0.9
  laser_offset: 0.25
  laser_max_range: 5000
  w_hit: 1.0
  ray_stepsize: 0.01
frame_id:
  fixed: world
  base: robot
  odom: odom
  laser: laser
files:
  data: robotdata1.log
  map: wean.dat
  path: /home/johnyao/Dropbox/Graduate_Coursework/RoboStats/robostats_lab1/
  #path: /home/vishnu/Documents/RoboStats/robostats_lab1/
