algorithm:
  num_particles: 1000
  sigma:
    dx: 0.02
    dy: 0.02
    dyaw: 0.03
frame_id:
  fixed: world
  base: robot
  odom: odom
  laser: laser
files:
  data: robotdata1.log
  map: wean.dat
  path: /home/johnyao/Dropbox/Graduate_Coursework/RoboStats/robostats_lab1/
